### ISSUE TITLE
ai = apiai.ApiAI(CLIENT_ACCESS_TOKEN)

### ISSUE THREAD

**Issue by dajor** [dialogflow/dialogflow-python-client#56]
Happens direct when i try to add the Token 

Traceback (most recent call last):
  File "send_user.py", line 66, in <module>
    main()
  File "send_user.py", line 34, in main
    ai = apiai.ApiAI(CLIENT_ACCESS_TOKEN)
TypeError: __init__() takes exactly 3 arguments (2 given)

**Comment by dajor** [comment]
ai = apiai.ApiAI(CLIENT_ACCESS_TOKEN.'') works
